name: Mon Premier Workflow

# Quand déclencher ce workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permet de lancer manuellement

# Les tâches à exécuter
jobs:
  saluer:
    runs-on: ubuntu-latest
    
    steps:
    - name: Dire bonjour
      run: echo "Hello World! Mon premier workflow fonctionne!"
    
    - name: Afficher la date
      run: date
    
    - name: Lister les fichiers
      run: ls -la
